::git fetch --all
::git checkout master
::git submodule foreach git fetch --all
::git submodule foreach git checkout master
::git pull origin master
::git submodule foreach git pull origin master

codegen\generateSDK.bat

codegen\pushSubmoduleChanges.bat "sdks/net" "https://Denis-Demenko:Rdflhfyn13@github.com/aspose-cad-cloud/aspose-cad-cloud-dotnet" master "denis.demenko@aspose.com" "Denis-Demenko"

git config user.email "denis.demenko@aspose.com"
git config user.name "Denis-Demenko"
git add -A
git commit -a -m "SDK regenerated by CI server"
git push "https://Denis-Demenko:Rdflhfyn13@github.com/aspose-cad-cloud/aspose-cad-cloud-codegen" master